### ISSUE TITLE
Continuous memory increase and panic - ostracon v1.0.7

### ISSUE THREAD

**Issue by zemyblue** [line/ostracon#457]
**Ostracon version** (use `ostracon version` or `git rev-parse --verify HEAD` if installed from source):
Ostracon v1.0.7-0.20220729051742-2231684789c6

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release): CentOS7
- **Install tools**: 
- **Others**:

**What happened**:
Continuous memory increase and panic.
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7a0ff9]

goroutine 29155274 [running]:
encoding/json.(*encodeState).marshal.func1(0xc1a7acf730)
        encoding/json/encode.go:328 +0x8d
panic(0x1fe8bc0, 0x3795460)
        runtime/panic.go:965 +0x1b9
encoding/hex.Encode(0xc17cdac340, 0x40, 0x40, 0x0, 0x20, 0x20, 0x900)
        encoding/hex/hex.go:27 +0x39
encoding/hex.EncodeToString(...)
        encoding/hex/hex.go:100
github.com/line/ostracon/libs/bytes.HexBytes.MarshalJSON(0x0, 0x20, 0x20, 0x426765, 0x1ffdb40, 0x20feb20, 0x20aaa00, 0x7ff1fb352488)
        github.com/line/ostracon@v1.0.7-0.20220729051742-2231684789c6/libs/bytes/bytes.go:25 +0xa5
encoding/json.addrMarshalerEncoder(0xc02e509c80, 0x20aaa40, 0xc0a7b8db30, 0x197, 0x100)
        encoding/json/encode.go:496 +0xe4
encoding/json.condAddrEncoder.encode(0x25162d0, 0x2516328, 0xc02e509c80, 0x20aaa40, 0xc0a7b8db30, 0x197, 0x100)
        encoding/json/encode.go:959 +0x6a
encoding/json.structEncoder.encode(0xc003da85a0, 0x2, 0x2, 0xc003d61d10, 0xc02e509c80, 0x21274c0, 0xc0a7b8db28, 0x199, 0x100)
        encoding/json/encode.go:761 +0x2ab
encoding/json.structEncoder.encode(0xc003df0900, 0xf, 0x10, 0xc00533b380, 0xc02e509c80, 0x2233720, 0xc0a7b8daf8, 0x199, 0x100)
        encoding/json/encode.go:761 +0x2ab
encoding/json.structEncoder.encode(0xc0053318c0, 0x2, 0x2, 0xc00533b4a0, 0xc02e509c80, 0x2132820, 0xc0a7b8dad0, 0x199, 0x1fc0100)
        encoding/json/encode.go:761 +0x2ab
encoding/json.ptrEncoder.encode(0xc00533b4d0, 0xc02e509c80, 0x2232120, 0xc0a7b8dad0, 0x16, 0x2230100)
        encoding/json/encode.go:944 +0x125
encoding/json.(*encodeState).reflectValue(0xc02e509c80, 0x2232120, 0xc0a7b8dad0, 0x16, 0xc1a7ac0100)
        encoding/json/encode.go:360 +0x82
encoding/json.(*encodeState).marshal(0xc02e509c80, 0x2232120, 0xc0a7b8dad0, 0x100, 0x0, 0x0)
        encoding/json/encode.go:332 +0xf9
encoding/json.Marshal(0x2232120, 0xc0a7b8dad0, 0x222aee0, 0xc197fda570, 0xc1a7acf8e0, 0x10926c8, 0xc197fda570)
        encoding/json/encode.go:161 +0x52
github.com/rs/zerolog.init.1.func1(0x2232120, 0xc0a7b8dad0, 0x7ff1fb141c60, 0xc005dba027, 0x2279a0e, 0x2, 0x0)
        github.com/rs/zerolog@v1.27.0/encoder_json.go:21 +0x3c
github.com/rs/zerolog/internal/json.Encoder.AppendInterface(0xc005dba000, 0x2b, 0x1000, 0x2232120, 0xc0a7b8dad0, 0xc005dba000, 0x2a, 0x1000)
        github.com/rs/zerolog@v1.27.0/internal/json/types.go:365 +0x46
github.com/rs/zerolog.appendFieldList(0xc005dba000, 0x2b, 0x1000, 0xc1a7acfb30, 0x2, 0x2, 0x2266380, 0xf, 0xc1a7acfb28)
        github.com/rs/zerolog@v1.27.0/fields.go:273 +0x4a5
github.com/rs/zerolog.appendFields(0xc005dba000, 0x25, 0x1000, 0x1fd0600, 0xc1a7acfc20, 0x27912a8, 0x155, 0x7ff1c81cdb60)
        github.com/rs/zerolog@v1.27.0/fields.go:31 +0x391
github.com/rs/zerolog.(*Event).Fields(...)
        github.com/rs/zerolog@v1.27.0/event.go:165
github.com/line/lbm-sdk/server.ZeroLogWrapper.Debug(0x27912a8, 0xc000fb84a0, 0x0, 0x0, 0x0, 0xc000160400, 0x15, 0x1f4, 0xc000fb84b0, 0x1, ...)
        github.com/line/lbm-sdk@v0.46.0-rc6/server/logger.go:38 +0x23a
github.com/line/ostracon/consensus.(*PeerState).PickSendVote(0xc0a7b8dad0, 0x27c0c48, 0xc0a0a2a3f0, 0x0)
        github.com/line/ostracon@v1.0.7-0.20220729051742-2231684789c6/consensus/reactor.go:1083 +0x14d
github.com/line/ostracon/consensus.(*Reactor).gossipVotesForHeight(0xc01a12f180, 0x27b1af8, 0xc005de7080, 0xc175c78dd0, 0xc1af5099a0, 0xc0a7b8dad0, 0xc004044f01)
        github.com/line/ostracon@v1.0.7-0.20220729051742-2231684789c6/consensus/reactor.go:759 +0x427
github.com/line/ostracon/consensus.(*Reactor).gossipVotesRoutine(0xc01a12f180, 0x27d5850, 0xc01616bd40, 0xc0a7b8dad0)
        github.com/line/ostracon@v1.0.7-0.20220729051742-2231684789c6/consensus/reactor.go:687 +0x8cf
created by github.com/line/ostracon/consensus.(*Reactor).AddPeer
        github.com/line/ostracon@v1.0.7-0.20220729051742-2231684789c6/consensus/reactor.go:203 +0x111
```

**CPU status**
<img width="888" alt="스크린샷 2022-08-27 오후 10 00 45" src="https://user-images.githubusercontent.com/3938725/187666427-c434b10b-0b92-414f-ac6a-8c75d7871e20.png">

**Mem status**
<img width="910" alt="스크린샷 2022-08-27 오후 10 00 55" src="https://user-images.githubusercontent.com/3938725/187666458-8736ca9a-5826-4592-b3ba-dcfb0dc53bab.png">

**What you expected to happen**:
No panic

**Have you tried the latest version**: Yes

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by tnasu** [comment]
Fixed by https://github.com/line/ostracon/pull/458
